name: IslandFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for IslandFreedom, an all-op server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
